// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Log

package domain

// LogSlice is a slice of type Log. Use it where you would use []Log.
type LogSlice []Log

// Where returns a new LogSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv LogSlice) Where(fn func(Log) bool) (result LogSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Count gives the number elements of LogSlice that return true for the passed func. See: http://clipperhouse.github.io/gen/#Count
func (rcv LogSlice) Count(fn func(Log) bool) (result int) {
	for _, v := range rcv {
		if fn(v) {
			result++
		}
	}
	return
}
