port: "8080"
csv_path: "data/"
static_files: "./statics"
secret_path: "../configs/private.key"
jwt_realm: "ofls"
admin_password: "ofls_pass"
cors_domains: 
  - "*"
cors_headers: 
  - "*"
cors_methods:
  - "GET"
  - "POST"
cors_allow_credentials: true
cors_max_age: 86400
